const API = 'http://localhost:8080/api';
let activeCuisine = '';
let menuFoods = [];
const user = () => JSON.parse(localStorage.getItem('foodUser') || 'null');
const headers = () => ({ 'Content-Type': 'application/json', ...(user() ? { 'X-User-Id': user().id } : {}) });
async function request(path, options = {}) {
  const response = await fetch(API + path, { ...options, headers: { ...headers(), ...(options.headers || {}) } });
  const data = response.status === 204 ? null : await response.json();
  if (!response.ok) throw new Error(data?.error || 'Request failed');
  return data;
}
const restaurantImage = name => name.toLowerCase().includes('spice') ? 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85' : 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85';
const foodImage = name => name.toLowerCase().includes('paneer') ? 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=700&q=85' : 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=700&q=85';
function nav() {
  const current = user();
  document.querySelector('#nav').innerHTML = `<nav class="navbar navbar-expand-lg"><div class="container"><a class="navbar-brand" href="index.html"><span class="brand-mark">Z</span>Zestora</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#links"><span class="navbar-toggler-icon"></span></button><div id="links" class="collapse navbar-collapse"><div class="navbar-nav ms-auto align-items-lg-center"><a class="nav-link" href="restaurants.html">Discover</a><a class="nav-link" href="cart.html">Cart</a>${current ? `<a class="nav-link" href="orders.html">Orders</a>${current.role === 'RESTAURANT_OWNER' ? '<a class="nav-link" href="restaurant-dashboard.html">Dashboard</a>' : ''}<span class="navbar-text ms-lg-3">Hi, ${current.fullName}</span><button class="btn btn-sm btn-outline-zest ms-lg-3" onclick="logout()">Logout</button>` : '<a class="nav-link" href="login.html">Login</a><a class="nav-link" href="restaurant-login.html">Partner login</a>'}</div></div></div></nav>`;
}
function logout() { localStorage.removeItem('foodUser'); location.href = 'index.html'; }
function showError(error) { const box = document.querySelector('#error'); if (box) { box.textContent = error.message; box.classList.remove('d-none'); } }
function requireUser() { if (!user()) location.href = 'login.html'; }
async function login(event) { event.preventDefault(); try { const form = new FormData(event.target); const result = await request('/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); localStorage.setItem('foodUser', JSON.stringify(result)); location.href = 'restaurants.html'; } catch (error) { showError(error); } }
async function register(event) { event.preventDefault(); try { const form = new FormData(event.target); await request('/auth/register', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); location.href = 'login.html'; } catch (error) { showError(error); } }
async function ownerLogin(event) { event.preventDefault(); try { const form = new FormData(event.target); const result = await request('/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); if (result.role !== 'RESTAURANT_OWNER') throw new Error('This account is not a restaurant owner account'); localStorage.setItem('foodUser', JSON.stringify(result)); location.href = 'restaurant-dashboard.html'; } catch (error) { showError(error); } }
async function registerOwner(event) { event.preventDefault(); try { const form = new FormData(event.target); const result = await request('/auth/owner/register', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); localStorage.setItem('foodUser', JSON.stringify(result)); location.href = 'restaurant-dashboard.html'; } catch (error) { showError(error); } }
function setCuisine(cuisine, button) { activeCuisine = cuisine; document.querySelectorAll('.category-chip').forEach(chip => chip.classList.remove('active')); button.classList.add('active'); loadRestaurants(); }
async function loadRestaurants() { try { const search = document.querySelector('#search').value; const rating = Number(document.querySelector('#ratingFilter').value || 0); const items = await request('/restaurants' + (search ? `?search=${encodeURIComponent(search)}` : '')); const filtered = items.filter(r => (!activeCuisine || (r.cuisineType || '').toLowerCase().includes(activeCuisine.toLowerCase())) && (!rating || Number(r.rating) >= rating)); document.querySelector('#resultCount').textContent = `${filtered.length} kitchen${filtered.length === 1 ? '' : 's'}`; document.querySelector('#restaurants').innerHTML = filtered.map(r => `<div class="col-md-6 col-xl-4"><article class="restaurant-card h-100"><img class="restaurant-image" src="${r.imageUrl || restaurantImage(r.name)}" alt="${r.name}"><div class="card-body"><div class="d-flex justify-content-between align-items-start"><span class="badge offer-badge">${r.name.includes('Spice') ? '20% off today' : 'Fresh pick'}</span><span class="rating">★ ${r.rating}</span></div><h5 class="mt-3 mb-1">${r.name}</h5><p class="text-muted mb-3">${r.cuisineType || 'Multi-cuisine'} · ${r.address}</p><div class="small text-muted mb-3">25-35 min &nbsp; · &nbsp; Free delivery over ₹299</div><a class="btn btn-zest w-100" href="menu.html?restaurantId=${r.id}">View menu <span class="float-end">→</span></a></div></article></div>`).join('') || '<div class="col-12"><div class="empty-state p-5 text-center">No kitchens match that search yet.</div></div>'; } catch (error) { showError(error); } }
async function loadMenu() { const id = new URLSearchParams(location.search).get('restaurantId'); try { const [restaurant, foods] = await Promise.all([request('/restaurants/' + id), request('/food-items?restaurantId=' + id)]); menuFoods = foods; document.title = `${restaurant.name} | Zestora`; document.querySelector('#menuHero').innerHTML = `<div class="col-md-5"><img src="${restaurant.imageUrl || restaurantImage(restaurant.name)}" alt="${restaurant.name}"></div><div class="col-md-7 menu-hero-copy"><p class="eyebrow">${restaurant.cuisineType || 'Local kitchen'}</p><h1>${restaurant.name}</h1><p class="lead">${restaurant.description || 'Made fresh, packed with flavour.'}</p><div><span class="rating">★ ${restaurant.rating}</span><span class="ms-3">25-35 min</span><span class="ms-3">Free delivery over ₹299</span></div></div>`; renderMenu(foods); } catch (error) { showError(error); } }
function renderMenu(foods) { document.querySelector('#menu').innerHTML = foods.map(f => `<div class="col-md-6"><article class="food-card h-100"><img class="food-image" src="${f.imageUrl || foodImage(f.name)}" alt="${f.name}"><div class="card-body"><div class="d-flex justify-content-between gap-3"><div><span class="badge veg-badge mb-2">${f.name.toLowerCase().includes('chicken') ? 'Non-veg' : 'Veg'}</span><h5>${f.name}</h5></div><span class="price">₹${Number(f.price).toFixed(0)}</span></div><p class="text-muted">${f.description || 'A Zestora favourite, prepared fresh to order.'}</p><button class="btn btn-outline-zest" onclick="addToCart(${f.id})">Add to cart +</button></div></article></div>`).join('') || '<div class="col-12"><div class="empty-state p-5 text-center">This menu is being refreshed.</div></div>'; }
function filterMenu() { const query = document.querySelector('#foodSearch').value.toLowerCase(); renderMenu(menuFoods.filter(food => food.name.toLowerCase().includes(query) || (food.description || '').toLowerCase().includes(query))); }
async function addToCart(foodItemId) { requireUser(); try { await request('/cart/items', { method: 'POST', body: JSON.stringify({ foodItemId, quantity: 1 }) }); alert('Added to cart'); } catch (error) { showError(error); } }
async function loadCart() { requireUser(); try { const cart = await request('/cart'); document.querySelector('#cart').innerHTML = cart.items.length ? cart.items.map(i => `<tr><td>${i.foodItem.name}</td><td>₹${i.foodItem.price}</td><td>${i.quantity}</td><td>₹${(i.foodItem.price * i.quantity).toFixed(2)}</td><td><button class="btn btn-sm btn-outline-danger" onclick="removeCart(${i.id})">Remove</button></td></tr>`).join('') : '<tr><td colspan="5">Your cart is empty.</td></tr>'; } catch (error) { showError(error); } }
async function removeCart(id) { await request('/cart/items/' + id, { method: 'DELETE' }); loadCart(); }
async function placeOrder(event) { event.preventDefault(); try { const form = new FormData(event.target); await request('/orders', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); location.href = 'orders.html'; } catch (error) { showError(error); } }
async function loadOrders() { requireUser(); try { const orders = await request('/orders'); document.querySelector('#orders').innerHTML = orders.map(o => `<div class="card mb-3"><div class="card-body d-flex justify-content-between"><div><h5>Order #${o.id}</h5><p class="mb-0">${o.items.map(i => `${i.itemName} × ${i.quantity}`).join(', ')}</p></div><div class="text-end"><span class="badge text-bg-primary status">${o.status}</span><div class="price mt-2">₹${o.totalAmount}</div></div></div></div>`).join('') || '<p>No orders yet.</p>'; } catch (error) { showError(error); } }
async function loadOwnerDashboard() { requireUser(); if (user().role !== 'RESTAURANT_OWNER') { location.href = 'restaurant-login.html'; return; } try { const restaurants = await request('/restaurants/owner/' + user().id); if (!restaurants.length) throw new Error('No restaurant is linked to this owner'); const restaurant = restaurants[0]; window.ownerRestaurantId = restaurant.id; document.querySelector('#ownerTitle').textContent = restaurant.name; document.querySelector('#restaurantDetails').innerHTML = `<div class="col-md-5"><img src="${restaurant.imageUrl || restaurantImage(restaurant.name)}" alt="${restaurant.name}"></div><div class="col-md-7 menu-hero-copy"><p class="eyebrow">${restaurant.cuisineType || 'Your kitchen'}</p><h1>${restaurant.name}</h1><p class="lead">${restaurant.description || ''}</p><p>${restaurant.address} · ${restaurant.phone || 'Phone not added'}</p></div>`; const categories = await request('/categories'); document.querySelector('#categoryId').innerHTML = categories.map(category => `<option value="${category.id}">${category.name}</option>`).join(''); await loadOwnerMenu(); } catch (error) { showError(error); } }
async function loadOwnerMenu() { const foods = await request('/food-items?restaurantId=' + window.ownerRestaurantId + '&availableOnly=false'); document.querySelector('#ownerMenu').innerHTML = foods.map(food => `<div class="col-md-6"><article class="food-card h-100"><div class="card-body"><div class="d-flex justify-content-between"><h5>${food.name}</h5><span class="price">₹${Number(food.price).toFixed(0)}</span></div><p class="text-muted">${food.description || ''}</p><span class="badge ${food.available ? 'veg-badge' : 'offer-badge'}">${food.available ? 'Available' : 'Unavailable'}</span><button class="btn btn-sm btn-outline-danger float-end" onclick="deleteFood(${food.id})">Delete</button></div></article></div>`).join('') || '<div class="col-12"><div class="empty-state p-4">No menu items yet. Add your first dish above.</div></div>'; }
async function saveFood(event) { event.preventDefault(); try { const form = new FormData(event.target); const values = Object.fromEntries(form); values.restaurantId = window.ownerRestaurantId; values.categoryId = Number(values.categoryId); values.price = Number(values.price); values.available = form.get('available') === 'on'; await request('/food-items', { method: 'POST', body: JSON.stringify(values) }); event.target.reset(); await loadOwnerMenu(); } catch (error) { showError(error); } }
async function deleteFood(id) { try { await request('/food-items/' + id, { method: 'DELETE' }); await loadOwnerMenu(); } catch (error) { showError(error); } }
document.addEventListener('DOMContentLoaded', () => { nav(); });
